{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterarticleratinghandlerprotocol\/articleratingvoteselected(_:at:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterarticleratinghandlerprotocol\/articleratingvoteselected(_:at:)"]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingHandlerProtocol\/articleRatingVoteSelected(_:at:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"articleRatingVoteSelected","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"ratingState","kind":"internalParam"},{"text":": (any ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingStateProtocol","preciseIdentifier":"c:objc(pl)ZDKHelpCenterArticleRatingStateProtocol","text":"ZDKHelpCenterArticleRatingStateProtocol","kind":"typeIdentifier"},{"text":")!, ","kind":"text"},{"text":"at","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingHandlerProtocol"]]},"metadata":{"externalID":"c:objc(pl)ZDKHelpCenterArticleRatingHandlerProtocol(im)articleRatingVoteSelected:atIndex:","role":"symbol","required":true,"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"SupportSDK"}],"title":"articleRatingVoteSelected(_:at:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"articleRatingVoteSelected","kind":"identifier"},{"text":"((any ","kind":"text"},{"text":"ZDKHelpCenterArticleRatingStateProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)ZDKHelpCenterArticleRatingStateProtocol"},{"text":")!, ","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"articleRatingVoteSelected:atIndex:","kind":"identifier"}]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterArticleRatingStateProtocol":{"role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterArticleRatingStateProtocol","kind":"identifier"}],"title":"ZDKHelpCenterArticleRatingStateProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterArticleRatingStateProtocol","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterarticleratingstateprotocol","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingStateProtocol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterArticleRatingHandlerProtocol":{"type":"topic","title":"ZDKHelpCenterArticleRatingHandlerProtocol","role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterArticleRatingHandlerProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingHandlerProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterArticleRatingHandlerProtocol","kind":"identifier"}],"abstract":[],"url":"\/documentation\/supportsdk\/zdkhelpcenterarticleratinghandlerprotocol","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterArticleRatingHandlerProtocol/articleRatingVoteSelected(_:at:)":{"required":true,"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterArticleRatingHandlerProtocol\/articleRatingVoteSelected(_:at:)","navigatorTitle":[{"text":"articleRatingVoteSelected:atIndex:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"articleRatingVoteSelected","kind":"identifier"},{"text":"((any ","kind":"text"},{"text":"ZDKHelpCenterArticleRatingStateProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)ZDKHelpCenterArticleRatingStateProtocol"},{"text":")!, ","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterarticleratinghandlerprotocol\/articleratingvoteselected(_:at:)","role":"symbol","type":"topic","kind":"symbol","abstract":[],"title":"articleRatingVoteSelected(_:at:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"articleRatingVoteSelected:atIndex:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"articleRatingVoteSelected:atIndex:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"articleRatingVoteSelected:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)ZDKHelpCenterArticleRatingStateProtocol","text":"id<ZDKHelpCenterArticleRatingStateProtocol>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"ratingState","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"atIndex:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"index","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingStateProtocol\/title","value":"ZDKHelpCenterArticleRatingStateProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingStateProtocol\/fragments","value":[{"text":"ZDKHelpCenterArticleRatingStateProtocol","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingStateProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKHelpCenterArticleRatingStateProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingHandlerProtocol\/title","value":"ZDKHelpCenterArticleRatingHandlerProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingHandlerProtocol\/fragments","value":[{"text":"ZDKHelpCenterArticleRatingHandlerProtocol","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingHandlerProtocol\/navigatorTitle","value":[{"text":"ZDKHelpCenterArticleRatingHandlerProtocol","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingHandlerProtocol~1articleRatingVoteSelected(_:at:)\/title","value":"articleRatingVoteSelected:atIndex:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterArticleRatingHandlerProtocol~1articleRatingVoteSelected(_:at:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"articleRatingVoteSelected:atIndex:","kind":"identifier"}]}]}]}