{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidSectionIds","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkhelpcentererror\/invalidsectionids"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkhelpcentererror\/invalidsectionids"]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/invalidSectionIds","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidSectionIds"}],"navigatorTitle":[{"text":"ZDKHelpCenterErrorInvalidSectionIds","kind":"identifier"}],"modules":[{"name":"SupportSDK"}],"title":"ZDKHelpCenterError.invalidSectionIds","roleHeading":"Case","externalID":"c:@E@ZDKHelpCenterError@ZDKHelpCenterErrorInvalidSectionIds","role":"symbol"},"abstract":[{"type":"text","text":"Section ids were not found in Help Center."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError"]]},"sections":[],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterError":{"navigatorTitle":[{"text":"ZDKHelpCenterError","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkhelpcentererror","kind":"symbol","title":"ZDKHelpCenterError","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterError","kind":"identifier"}],"abstract":[{"type":"text","text":"Help Center error codes."}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterError/invalidSectionIds":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterError\/invalidSectionIds","url":"\/documentation\/supportsdk\/zdkhelpcentererror\/invalidsectionids","title":"ZDKHelpCenterError.invalidSectionIds","abstract":[{"text":"Section ids were not found in Help Center.","type":"text"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidSectionIds","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ZDKHelpCenterErrorInvalidSectionIds","kind":"identifier"}],"role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKHelpCenterErrorInvalidSectionIds","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterErrorInvalidSectionIds"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ZDKHelpCenterErrorInvalidSectionIds"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKHelpCenterError","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError\/title"},{"op":"replace","value":[{"text":"ZDKHelpCenterError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError\/fragments"},{"op":"replace","value":[{"text":"ZDKHelpCenterError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError\/navigatorTitle"},{"op":"replace","value":"ZDKHelpCenterErrorInvalidSectionIds","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError~1invalidSectionIds\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterErrorInvalidSectionIds"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterError~1invalidSectionIds\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}