{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate\/conversationsbarbuttonimage()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate\/conversationsbarbuttonimage()"]}],"metadata":{"title":"conversationsBarButtonImage()","roleHeading":"Instance Method","role":"symbol","externalID":"c:objc(pl)ZDKHelpCenterConversationsUIDelegate(im)conversationsBarButtonImage","navigatorTitle":[{"text":"conversationsBarButtonImage","kind":"identifier"}],"platforms":[{"beta":false,"deprecated":true,"unavailable":false,"message":"use ZDKHelpCenterUiConfiguration and ZDKArticleUiConfiguration to configure the 'contact us' button on their respective screens "}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationsBarButtonImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"modules":[{"name":"SupportSDK"}],"symbolKind":"method"},"abstract":[{"text":"To conform implementations should return an image for the right nav bar button.","type":"text"}],"kind":"symbol","deprecationSummary":[{"inlineContent":[{"type":"text","text":"use ZDKHelpCenterUiConfiguration and ZDKArticleUiConfiguration to configure the 'contact us' button on their respective screens "}],"type":"paragraph"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationsBarButtonImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"!","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"An image for the right nav bar button.","type":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate\/conversationsBarButtonImage()"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterConversationsUIDelegate/conversationsBarButtonImage()":{"kind":"symbol","title":"conversationsBarButtonImage()","url":"\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate\/conversationsbarbuttonimage()","abstract":[{"type":"text","text":"To conform implementations should return an image for the right nav bar button."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate\/conversationsBarButtonImage()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"conversationsBarButtonImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"!","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"conversationsBarButtonImage","kind":"identifier"}],"deprecated":true,"role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterConversationsUIDelegate":{"abstract":[],"navigatorTitle":[{"text":"ZDKHelpCenterConversationsUIDelegate","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate","deprecated":true,"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterConversationsUIDelegate","kind":"identifier"}],"title":"ZDKHelpCenterConversationsUIDelegate","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"unavailable":false,"beta":false,"deprecated":true}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"conversationsBarButtonImage","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"conversationsBarButtonImage","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"text":"conversationsBarButtonImage","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"An image for the right nav bar button.","type":"text"}]}]},"op":"replace"},{"path":"\/deprecationSummary","value":[{"inlineContent":[{"text":"use ZDKHelpCenterUiConfiguration and ZDKArticleUiConfiguration to configure the 'contact us' button on their respective screens ","type":"text"}],"type":"paragraph"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate~1conversationsBarButtonImage()\/title","value":"conversationsBarButtonImage","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate~1conversationsBarButtonImage()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"conversationsBarButtonImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate\/title","value":"ZDKHelpCenterConversationsUIDelegate","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate\/fragments","value":[{"kind":"identifier","text":"ZDKHelpCenterConversationsUIDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"ZDKHelpCenterConversationsUIDelegate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}