{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate\/navBarConversationsUIType()","interfaceLanguage":"swift"},"deprecationSummary":[{"inlineContent":[{"type":"text","text":"use ZDKHelpCenterUiConfiguration and ZDKArticleUiConfiguration to configure the 'contact us' button on their respective screens "}],"type":"paragraph"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate"]]},"metadata":{"platforms":[{"message":"use ZDKHelpCenterUiConfiguration and ZDKArticleUiConfiguration to configure the 'contact us' button on their respective screens ","deprecated":true,"unavailable":false,"beta":false}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:objc(pl)ZDKHelpCenterConversationsUIDelegate(im)navBarConversationsUIType","symbolKind":"method","title":"navBarConversationsUIType()","navigatorTitle":[{"text":"navBarConversationsUIType","kind":"identifier"}],"modules":[{"name":"SupportSDK"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"navBarConversationsUIType","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"ZDKNavBarConversationsUIType","preciseIdentifier":"c:@E@ZDKNavBarConversationsUIType","kind":"typeIdentifier"}],"required":true},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"navBarConversationsUIType","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"ZDKNavBarConversationsUIType","kind":"typeIdentifier","preciseIdentifier":"c:@E@ZDKNavBarConversationsUIType"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The ZDKNavBarConversationsUIType to display."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate\/navbarconversationsuitype()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate\/navbarconversationsuitype()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"To conform implementations should return the conversations UI type desired.","type":"text"}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterConversationsUIDelegate":{"abstract":[],"navigatorTitle":[{"text":"ZDKHelpCenterConversationsUIDelegate","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate","deprecated":true,"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterConversationsUIDelegate","kind":"identifier"}],"title":"ZDKHelpCenterConversationsUIDelegate","type":"topic","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterConversationsUIDelegate/navBarConversationsUIType()":{"deprecated":true,"kind":"symbol","url":"\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate\/navbarconversationsuitype()","role":"symbol","required":true,"abstract":[{"type":"text","text":"To conform implementations should return the conversations UI type desired."}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate\/navBarConversationsUIType()","title":"navBarConversationsUIType()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"navBarConversationsUIType","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"ZDKNavBarConversationsUIType","kind":"typeIdentifier","preciseIdentifier":"c:@E@ZDKNavBarConversationsUIType"}],"navigatorTitle":[{"text":"navBarConversationsUIType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"deprecated":true,"unavailable":false,"beta":false}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"navBarConversationsUIType","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"navBarConversationsUIType","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"ZDKNavBarConversationsUIType","kind":"typeIdentifier","preciseIdentifier":"c:@E@ZDKNavBarConversationsUIType"},{"text":") ","kind":"text"},{"text":"navBarConversationsUIType","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The ZDKNavBarConversationsUIType to display."}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":[{"inlineContent":[{"text":"use ZDKHelpCenterUiConfiguration and ZDKArticleUiConfiguration to configure the 'contact us' button on their respective screens ","type":"text"}],"type":"paragraph"}],"path":"\/deprecationSummary","op":"replace"},{"value":"ZDKHelpCenterConversationsUIDelegate","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate\/title","op":"replace"},{"value":[{"text":"ZDKHelpCenterConversationsUIDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate\/fragments","op":"replace"},{"value":[{"text":"ZDKHelpCenterConversationsUIDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate\/navigatorTitle","op":"replace"},{"value":"navBarConversationsUIType","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate~1navBarConversationsUIType()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"navBarConversationsUIType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate~1navBarConversationsUIType()\/fragments","op":"replace"}]}]}