{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"title":"initialize(withZendesk:)","navigatorTitle":[{"text":"initializeWithZendesk:","kind":"identifier"}],"modules":[{"name":"SupportSDK"}],"roleHeading":"Type Method","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withZendesk","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Zendesk","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":[{"beta":false,"renamed":"Support","deprecated":true,"unavailable":false}],"externalID":"c:@M@SupportSDK@objc(cs)ZDKSupportUI(cm)initializeWithZendesk:","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withZendesk","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"zendesk","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Zendesk","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk"},{"kind":"text","text":"?)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI"]]},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI\/initialize(withZendesk:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/supportsdk\/supportui\/initialize(withzendesk:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/supportui\/initialize(withzendesk:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Initialize the SupportUI singleton with the Zendesk singleton","type":"text"},{"text":" ","type":"text"},{"text":"from ZendeskCoreSDK","type":"text"}],"sections":[],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportUI":{"abstract":[],"deprecated":true,"role":"symbol","kind":"symbol","url":"\/documentation\/supportsdk\/supportui","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupportUI","kind":"identifier"}],"title":"SupportUI","navigatorTitle":[{"text":"SupportUI","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportUI/initialize(withZendesk:)":{"type":"topic","title":"initialize(withZendesk:)","abstract":[{"text":"Initialize the SupportUI singleton with the Zendesk singleton","type":"text"},{"text":" ","type":"text"},{"text":"from ZendeskCoreSDK","type":"text"}],"navigatorTitle":[{"text":"initializeWithZendesk:","kind":"identifier"}],"kind":"symbol","deprecated":true,"url":"\/documentation\/supportsdk\/supportui\/initialize(withzendesk:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withZendesk","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Zendesk","preciseIdentifier":"c:@M@ZendeskCoreSDK@objc(cs)ZDKClassicZendesk","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI\/initialize(withZendesk:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"unavailable":false,"deprecated":true,"beta":false}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initializeWithZendesk:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"initializeWithZendesk:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"initializeWithZendesk:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ZDKClassicZendesk","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKClassicZendesk"},{"text":" *) ","kind":"text"},{"text":"zendesk","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKSupportUI","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI\/title"},{"value":[{"text":"ZDKSupportUI","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI\/fragments"},{"value":[{"kind":"identifier","text":"ZDKSupportUI"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI\/navigatorTitle"},{"value":"initializeWithZendesk:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI~1initialize(withZendesk:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"initializeWithZendesk:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI~1initialize(withZendesk:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}