{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Get the API instance (singleton)."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instance","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI","preciseIdentifier":"c:@M@SupportSDK@objc(cs)ZDKSupportUI","text":"SupportUI","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/supportui\/instance"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/supportui\/instance"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI\/instance"},"metadata":{"roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instance","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SupportUI","preciseIdentifier":"c:@M@SupportSDK@objc(cs)ZDKSupportUI","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"SupportSDK"}],"platforms":[{"renamed":"Support","unavailable":false,"deprecated":true,"beta":false}],"role":"symbol","externalID":"c:@M@SupportSDK@objc(cs)ZDKSupportUI(cpy)instance","symbolKind":"property","navigatorTitle":[{"text":"instance","kind":"identifier"}],"title":"instance"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportUI":{"abstract":[],"deprecated":true,"role":"symbol","kind":"symbol","url":"\/documentation\/supportsdk\/supportui","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SupportUI","kind":"identifier"}],"title":"SupportUI","navigatorTitle":[{"text":"SupportUI","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportUI/instance":{"abstract":[{"text":"Get the API instance (singleton).","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI\/instance","title":"instance","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"instance","kind":"identifier"}],"deprecated":true,"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instance","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@SupportSDK@objc(cs)ZDKSupportUI","text":"SupportUI","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/supportsdk\/supportui\/instance","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"beta":false,"deprecated":true}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"instance","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"instance","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"ZDKSupportUI","kind":"typeIdentifier","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportUI","preciseIdentifier":"c:@M@SupportSDK@objc(cs)ZDKSupportUI"},{"text":" * ","kind":"text"},{"text":"instance","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ZDKSupportUI","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI\/title","op":"replace"},{"value":[{"text":"ZDKSupportUI","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKSupportUI"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI\/navigatorTitle","op":"replace"},{"value":"instance","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI~1instance\/title","op":"replace"},{"value":[{"kind":"identifier","text":"instance"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportUI~1instance\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}