{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Decide based on the contents of the nav stack whether to pop","type":"text"},{"text":" ","type":"text"},{"text":"the given view controller off the stack, or whether to","type":"text"},{"text":" ","type":"text"},{"text":"dismiss the given view controller.","type":"text"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/DismissUtil\/remove(_:from:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/DismissUtil"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?, ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"navigationController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UINavigationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UINavigationController"},{"text":"?)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"viewController","content":[{"inlineContent":[{"type":"text","text":"A view controller which should be removed from a screen."}],"type":"paragraph"}]},{"name":"navigationController","content":[{"inlineContent":[{"text":"A navigation controller for inspection.","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/supportsdk\/dismissutil\/remove(_:from:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/dismissutil\/remove(_:from:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"remove:from:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Type Method","role":"symbol","externalID":"c:@M@SupportSDK@objc(cs)ZDKDismissUtil(cm)remove:from:","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"modules":[{"name":"SupportSDK"}],"title":"remove(_:from:)"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/DismissUtil/remove(_:from:)":{"abstract":[{"type":"text","text":"Decide based on the contents of the nav stack whether to pop"},{"type":"text","text":" "},{"type":"text","text":"the given view controller off the stack, or whether to"},{"type":"text","text":" "},{"type":"text","text":"dismiss the given view controller."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/DismissUtil\/remove(_:from:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"remove:from:"}],"kind":"symbol","role":"symbol","title":"remove(_:from:)","url":"\/documentation\/supportsdk\/dismissutil\/remove(_:from:)","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/DismissUtil":{"navigatorTitle":[{"text":"DismissUtil","kind":"identifier"}],"role":"symbol","url":"\/documentation\/supportsdk\/dismissutil","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/DismissUtil","title":"DismissUtil","abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DismissUtil","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"remove:from:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"remove:from:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"remove:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"from:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UINavigationController","preciseIdentifier":"c:objc(cs)UINavigationController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"navigationController","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"text":"A view controller which should be removed from a screen.","type":"text"}]}]},{"name":"navigationController","content":[{"inlineContent":[{"type":"text","text":"A navigation controller for inspection."}],"type":"paragraph"}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1DismissUtil~1remove(_:from:)\/title","op":"replace","value":"remove:from:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1DismissUtil~1remove(_:from:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"remove:from:"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1DismissUtil\/title","op":"replace","value":"ZDKDismissUtil"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1DismissUtil\/fragments","op":"replace","value":[{"text":"ZDKDismissUtil","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1DismissUtil\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKDismissUtil"}]}]}]}