{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestUi(requestId:)"},"kind":"symbol","sections":[],"abstract":[{"text":"Build the Request Ui. This allows users to create and respond to individual tickets.","type":"text"}],"variants":[{"paths":["\/documentation\/supportsdk\/requestui\/buildrequestui(requestid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/requestui\/buildrequestui(requestid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"buildRequestUiWithRequestId:","kind":"identifier"}],"title":"buildRequestUi(requestId:)","roleHeading":"Type Method","symbolKind":"method","role":"symbol","modules":[{"name":"SupportSDK"}],"externalID":"c:@M@SupportSDK@objc(cs)ZDKRequestUi(cm)buildRequestUiWithRequestId:","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buildRequestUi","kind":"identifier"},{"text":"(","kind":"text"},{"text":"requestId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildRequestUi"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}]}],"kind":"declarations"},{"parameters":[{"name":"requestId","content":[{"type":"paragraph","inlineContent":[{"text":"The ID of the ticket to display.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"aside","name":"Version","content":[{"inlineContent":[{"type":"text","text":"2.0.0"}],"type":"paragraph"}],"style":"note"}],"kind":"content"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUi/buildRequestUi(requestId:)":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buildRequestUi","kind":"identifier"},{"text":"(","kind":"text"},{"text":"requestId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi\/buildRequestUi(requestId:)","title":"buildRequestUi(requestId:)","type":"topic","abstract":[{"text":"Build the Request Ui. This allows users to create and respond to individual tickets.","type":"text"}],"navigatorTitle":[{"text":"buildRequestUiWithRequestId:","kind":"identifier"}],"url":"\/documentation\/supportsdk\/requestui\/buildrequestui(requestid:)","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/RequestUi":{"navigatorTitle":[{"kind":"identifier","text":"RequestUi"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/RequestUi","url":"\/documentation\/supportsdk\/requestui","abstract":[{"text":"Used to build view controller for ticketing. The returned objects must be presented inside a UINavigationController.","type":"text"},{"text":" ","type":"text"},{"text":"The containing navigation controller can be presented any way you see fit.","type":"text"}],"title":"RequestUi","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RequestUi"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"buildRequestUiWithRequestId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"buildRequestUiWithRequestId:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"buildRequestUiWithRequestId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"requestId"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"requestId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ID of the ticket to display."}]}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi~1buildRequestUi(requestId:)\/title","value":"buildRequestUiWithRequestId:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi~1buildRequestUi(requestId:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildRequestUiWithRequestId:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi\/title","value":"ZDKRequestUi"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi\/fragments","value":[{"kind":"identifier","text":"ZDKRequestUi"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1RequestUi\/navigatorTitle","value":[{"text":"ZDKRequestUi","kind":"identifier"}]}]}]}