{"abstract":[{"text":"The height of a separator for retina and none retina screens.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/separatorHeightForScreenScale()"},"sections":[],"metadata":{"title":"separatorHeightForScreenScale()","roleHeading":"Type Method","navigatorTitle":[{"text":"separatorHeightForScreenScale","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)ZDKUIUtil(cm)separatorHeightForScreenScale","modules":[{"name":"SupportSDK"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"separatorHeightForScreenScale"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"symbolKind":"method"},"variants":[{"paths":["\/documentation\/supportsdk\/zdkuiutil\/separatorheightforscreenscale()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/zdkuiutil\/separatorheightforscreenscale()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"separatorHeightForScreenScale","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"Height of separator.","type":"text"}]}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil/separatorHeightForScreenScale()":{"title":"separatorHeightForScreenScale()","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil\/separatorHeightForScreenScale()","role":"symbol","navigatorTitle":[{"text":"separatorHeightForScreenScale","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkuiutil\/separatorheightforscreenscale()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"separatorHeightForScreenScale","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The height of a separator for retina and none retina screens."}],"kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKUIUtil":{"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKUIUtil","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKUIUtil","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkuiutil","kind":"symbol","navigatorTitle":[{"text":"ZDKUIUtil","kind":"identifier"}],"title":"ZDKUIUtil"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"separatorHeightForScreenScale","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"separatorHeightForScreenScale","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"text":") ","kind":"text"},{"text":"separatorHeightForScreenScale","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"Height of separator.","type":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"separatorHeightForScreenScale","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1separatorHeightForScreenScale()\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"separatorHeightForScreenScale","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil~1separatorHeightForScreenScale()\/fragments"},{"value":"ZDKUIUtil","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil\/title"},{"value":[{"text":"ZDKUIUtil","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil\/fragments"},{"value":[{"text":"ZDKUIUtil","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKUIUtil\/navigatorTitle"}]}]}