{"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterOverview(withConfigs:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenteroverview(withconfigs:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenteroverview(withconfigs:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"platforms":[{"unavailable":false,"deprecated":true,"message":"use buildHelpCenterOverviewUiWithConfigs instead","beta":false}],"title":"buildHelpCenterOverview(withConfigs:)","modules":[{"name":"SupportSDK"}],"externalID":"c:objc(cs)ZDKHelpCenterUi(cm)buildHelpCenterOverviewWithConfigs:","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buildHelpCenterOverview","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withConfigs","kind":"externalParam"},{"text":": [any ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"text":"]) -> any ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" & ","kind":"text"},{"text":"ZDKHelpCenterDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate"}],"roleHeading":"Type Method","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"buildHelpCenterOverviewWithConfigs:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi"]]},"deprecationSummary":[{"inlineContent":[{"text":"use buildHelpCenterOverviewUiWithConfigs instead","type":"text"}],"type":"paragraph"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterOverview"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withConfigs"},{"kind":"text","text":" "},{"kind":"internalParam","text":"configs"},{"kind":"text","text":": [any "},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration"},{"kind":"text","text":"]) -> any "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"ZDKHelpCenterDelegate","preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate"}],"platforms":["iOS"]}]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi","url":"\/documentation\/supportsdk\/zdkhelpcenterui","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterUi"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterUi"}],"role":"symbol","abstract":[],"title":"ZDKHelpCenterUi"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/buildHelpCenterOverview(withConfigs:)":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterOverview(withConfigs:)","kind":"symbol","type":"topic","url":"\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenteroverview(withconfigs:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buildHelpCenterOverview","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withConfigs","kind":"externalParam"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:@M@SDKConfigurations@objc(pl)ZDKConfiguration","text":"Configuration","kind":"typeIdentifier"},{"text":"]) -> any ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate","text":"ZDKHelpCenterDelegate","kind":"typeIdentifier"}],"deprecated":true,"navigatorTitle":[{"text":"buildHelpCenterOverviewWithConfigs:","kind":"identifier"}],"role":"symbol","abstract":[],"title":"buildHelpCenterOverview(withConfigs:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDelegate":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterDelegate","kind":"identifier"}],"kind":"symbol","title":"ZDKHelpCenterDelegate","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate","role":"symbol","url":"\/documentation\/supportsdk\/zdkhelpcenterdelegate","navigatorTitle":[{"text":"ZDKHelpCenterDelegate","kind":"identifier"}],"deprecated":true,"abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"deprecated":true,"unavailable":false,"beta":false}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"buildHelpCenterOverviewWithConfigs:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"buildHelpCenterOverviewWithConfigs:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"UIViewController<ZDKHelpCenterDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)UIViewControllerobjc(pl)ZDKHelpCenterDelegate"},{"text":" *) ","kind":"text"},{"text":"buildHelpCenterOverviewWithConfigs:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<id<ZDKConfiguration>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"configs","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":[{"type":"paragraph","inlineContent":[{"text":"use buildHelpCenterOverviewUiWithConfigs instead","type":"text"}]}],"op":"replace","path":"\/deprecationSummary"},{"value":"ZDKHelpCenterUi","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/title"},{"value":[{"text":"ZDKHelpCenterUi","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/fragments"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterUi"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/navigatorTitle"},{"value":"buildHelpCenterOverviewWithConfigs:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterOverview(withConfigs:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterOverviewWithConfigs:"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterOverview(withConfigs:)\/fragments"},{"value":"ZDKHelpCenterDelegate","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate\/title"},{"value":[{"text":"ZDKHelpCenterDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate\/fragments"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}