{"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticleUi(withArticleId:)","interfaceLanguage":"swift"},"metadata":{"title":"buildHelpCenterArticleUi(withArticleId:)","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterArticleUiWithArticleId:"}],"role":"symbol","modules":[{"name":"SupportSDK"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buildHelpCenterArticleUi","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withArticleId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"symbolKind":"method","externalID":"c:objc(cs)ZDKHelpCenterUi(cm)buildHelpCenterArticleUiWithArticleId:"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi"]]},"abstract":[{"type":"text","text":"Build the Help Center Article view controller. Displays a single article."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buildHelpCenterArticleUi","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withArticleId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"articleId","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ID of a Help Center article. This is fetched and displayed."}]}],"name":"articleId"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticleui(witharticleid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticleui(witharticleid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi","url":"\/documentation\/supportsdk\/zdkhelpcenterui","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterUi"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterUi"}],"role":"symbol","abstract":[],"title":"ZDKHelpCenterUi"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/buildHelpCenterArticleUi(withArticleId:)":{"role":"symbol","navigatorTitle":[{"text":"buildHelpCenterArticleUiWithArticleId:","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticleUi(withArticleId:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buildHelpCenterArticleUi","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withArticleId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}],"title":"buildHelpCenterArticleUi(withArticleId:)","kind":"symbol","type":"topic","url":"\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticleui(witharticleid:)","abstract":[{"text":"Build the Help Center Article view controller. Displays a single article.","type":"text"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"buildHelpCenterArticleUiWithArticleId:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterArticleUiWithArticleId:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"text":"buildHelpCenterArticleUiWithArticleId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"articleId","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"articleId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ID of a Help Center article. This is fetched and displayed."}]}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/title","value":"ZDKHelpCenterUi"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/fragments","value":[{"text":"ZDKHelpCenterUi","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/navigatorTitle","value":[{"text":"ZDKHelpCenterUi","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticleUi(withArticleId:)\/title","value":"buildHelpCenterArticleUiWithArticleId:"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticleUi(withArticleId:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"buildHelpCenterArticleUiWithArticleId:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}