{"variants":[{"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticle(witharticleid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticle(witharticleid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"SupportSDK"}],"platforms":[{"beta":false,"deprecated":true,"unavailable":false,"message":"use buildHelpCenterArticleUiWithArticleId instead"}],"title":"buildHelpCenterArticle(withArticleId:)","navigatorTitle":[{"kind":"identifier","text":"buildHelpCenterArticleWithArticleId:"}],"roleHeading":"Type Method","symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterArticle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withArticleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> any "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":" & "},{"kind":"typeIdentifier","text":"ZDKHelpCenterDelegate","preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate"}],"externalID":"c:objc(cs)ZDKHelpCenterUi(cm)buildHelpCenterArticleWithArticleId:"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"buildHelpCenterArticle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withArticleId","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"articleId","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> any ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":" & ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate","preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate","text":"ZDKHelpCenterDelegate","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticle(withArticleId:)","interfaceLanguage":"swift"},"kind":"symbol","deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"use buildHelpCenterArticleUiWithArticleId instead"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi","url":"\/documentation\/supportsdk\/zdkhelpcenterui","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterUi"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterUi"}],"role":"symbol","abstract":[],"title":"ZDKHelpCenterUi"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterUi/buildHelpCenterArticle(withArticleId:)":{"abstract":[],"deprecated":true,"title":"buildHelpCenterArticle(withArticleId:)","type":"topic","url":"\/documentation\/supportsdk\/zdkhelpcenterui\/buildhelpcenterarticle(witharticleid:)","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterUi\/buildHelpCenterArticle(withArticleId:)","kind":"symbol","navigatorTitle":[{"text":"buildHelpCenterArticleWithArticleId:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"buildHelpCenterArticle"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withArticleId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":") -> any "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":" & ","kind":"text"},{"text":"ZDKHelpCenterDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)ZDKHelpCenterDelegate"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterDelegate":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterDelegate","kind":"identifier"}],"kind":"symbol","title":"ZDKHelpCenterDelegate","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterDelegate","role":"symbol","url":"\/documentation\/supportsdk\/zdkhelpcenterdelegate","navigatorTitle":[{"text":"ZDKHelpCenterDelegate","kind":"identifier"}],"deprecated":true,"abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"beta":false,"deprecated":true,"unavailable":false}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"buildHelpCenterArticleWithArticleId:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterArticleWithArticleId:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)UIViewControllerobjc(pl)ZDKHelpCenterDelegate","text":"UIViewController<ZDKHelpCenterDelegate>"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"buildHelpCenterArticleWithArticleId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"articleId"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":[{"inlineContent":[{"type":"text","text":"use buildHelpCenterArticleUiWithArticleId instead"}],"type":"paragraph"}],"path":"\/deprecationSummary","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/title","op":"replace","value":"ZDKHelpCenterUi"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterUi"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi\/navigatorTitle","op":"replace","value":[{"text":"ZDKHelpCenterUi","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticle(withArticleId:)\/title","op":"replace","value":"buildHelpCenterArticleWithArticleId:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterUi~1buildHelpCenterArticle(withArticleId:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"buildHelpCenterArticleWithArticleId:"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate\/title","op":"replace","value":"ZDKHelpCenterDelegate"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate\/fragments","op":"replace","value":[{"text":"ZDKHelpCenterDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterDelegate\/navigatorTitle","op":"replace","value":[{"text":"ZDKHelpCenterDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}