{"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChild\/childDelegate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChild"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"childDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ContainerChildControllerDelegate","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/supportsdk\/containerchild\/childdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/containerchild\/childdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"property","role":"symbol","title":"childDelegate","modules":[{"name":"SupportSDK"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"childDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ContainerChildControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate"},{"text":"?","kind":"text"}],"externalID":"c:@M@SupportSDK@objc(pl)ZDKContainerChild(py)childDelegate","navigatorTitle":[{"text":"childDelegate","kind":"identifier"}],"roleHeading":"Instance Property"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChildControllerDelegate":{"abstract":[],"role":"symbol","type":"topic","title":"ContainerChildControllerDelegate","url":"\/documentation\/supportsdk\/containerchildcontrollerdelegate","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate","navigatorTitle":[{"text":"ContainerChildControllerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContainerChildControllerDelegate","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChild":{"title":"ContainerChild","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChild","url":"\/documentation\/supportsdk\/containerchild","navigatorTitle":[{"kind":"identifier","text":"ContainerChild"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContainerChild"}],"kind":"symbol","abstract":[],"role":"symbol","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChild/childDelegate":{"abstract":[],"navigatorTitle":[{"text":"childDelegate","kind":"identifier"}],"kind":"symbol","type":"topic","title":"childDelegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"childDelegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ContainerChildControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChild\/childDelegate","url":"\/documentation\/supportsdk\/containerchild\/childdelegate","required":true,"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"childDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"childDelegate","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<ZDKContainerChildControllerDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate"},{"text":" ","kind":"text"},{"text":"childDelegate","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/title","op":"replace","value":"ZDKContainerChildControllerDelegate"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/fragments","op":"replace","value":[{"text":"ZDKContainerChildControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/navigatorTitle","op":"replace","value":[{"text":"ZDKContainerChildControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChild\/title","op":"replace","value":"ZDKContainerChild"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChild\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKContainerChild"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChild\/navigatorTitle","op":"replace","value":[{"text":"ZDKContainerChild","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChild~1childDelegate\/title","op":"replace","value":"childDelegate"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChild~1childDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"childDelegate"}]}]}]}