{"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/word","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType"]]},"kind":"symbol","metadata":{"modules":[{"name":"SupportSDK"}],"externalID":"c:@M@SupportSDK@E@ZDKFileType@ZDKFileTypeWord","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"word"}],"title":"FileType.word","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypeWord"}],"symbolKind":"case","role":"symbol"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"word"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/supportsdk\/filetype\/word"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/filetype\/word"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType/word":{"url":"\/documentation\/supportsdk\/filetype\/word","type":"topic","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"word"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType\/word","navigatorTitle":[{"kind":"identifier","text":"ZDKFileTypeWord"}],"title":"FileType.word"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/FileType":{"role":"symbol","title":"FileType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FileType","kind":"identifier"}],"navigatorTitle":[{"text":"FileType","kind":"identifier"}],"url":"\/documentation\/supportsdk\/filetype","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/FileType","kind":"symbol","abstract":[{"type":"text","text":"Enum that represents the file types that zendesk supports"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKFileTypeWord","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ZDKFileTypeWord","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"ZDKFileTypeWord"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKFileTypeWord","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1word\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKFileTypeWord"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType~1word\/fragments"},{"op":"replace","value":"ZDKFileType","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/title"},{"op":"replace","value":[{"text":"ZDKFileType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKFileType"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1FileType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}