{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"present","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildController","text":"ContainerChildController","preciseIdentifier":"s:10SupportSDK24ContainerChildControllera","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"containerDelegate","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate","text":"ContainerChildControllerDelegate","preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/coordinator\/start(present:with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/coordinator\/start(present:with:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Coordinator\/start(present:with:)"},"metadata":{"role":"symbol","title":"start(present:with:)","symbolKind":"method","modules":[{"name":"SupportSDK"}],"externalID":"c:@M@SupportSDK@objc(pl)ZDKCoordinator(im)startWithPresent:with:","roleHeading":"Instance Method","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"present","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"ContainerChildController","preciseIdentifier":"s:10SupportSDK24ContainerChildControllera","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ContainerChildControllerDelegate","preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"startWithPresent:with:","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Coordinator"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Coordinator":{"role":"symbol","navigatorTitle":[{"text":"Coordinator","kind":"identifier"}],"title":"Coordinator","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinator","kind":"identifier"}],"url":"\/documentation\/supportsdk\/coordinator","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Coordinator"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChildControllerDelegate":{"abstract":[],"role":"symbol","type":"topic","title":"ContainerChildControllerDelegate","url":"\/documentation\/supportsdk\/containerchildcontrollerdelegate","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate","navigatorTitle":[{"text":"ContainerChildControllerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContainerChildControllerDelegate","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/Coordinator/start(present:with:)":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/Coordinator\/start(present:with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"(","kind":"text"},{"text":"present","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"ContainerChildController","kind":"typeIdentifier","preciseIdentifier":"s:10SupportSDK24ContainerChildControllera"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ContainerChildControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate"},{"text":")","kind":"text"}],"title":"start(present:with:)","type":"topic","abstract":[],"required":true,"url":"\/documentation\/supportsdk\/coordinator\/start(present:with:)","role":"symbol","navigatorTitle":[{"text":"startWithPresent:with:","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChildController":{"abstract":[],"title":"ContainerChildController","url":"\/documentation\/supportsdk\/containerchildcontroller","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContainerChildController"}],"navigatorTitle":[{"kind":"identifier","text":"ContainerChildController"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildController"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"startWithPresent:with:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"startWithPresent:with:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"startWithPresent:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"text":"UIViewController<ZDKContainerChild>","preciseIdentifier":"c:Q$objc(cs)UIViewController@M@SupportSDK@objc(pl)ZDKContainerChild","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"present","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"with:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<ZDKContainerChildControllerDelegate>","preciseIdentifier":"c:Qo@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"containerDelegate","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ZDKCoordinator","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Coordinator\/title"},{"value":[{"text":"ZDKCoordinator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Coordinator\/fragments"},{"value":[{"text":"ZDKCoordinator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Coordinator\/navigatorTitle"},{"value":"ZDKContainerChildControllerDelegate","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/title"},{"value":[{"text":"ZDKContainerChildControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/fragments"},{"value":[{"kind":"identifier","text":"ZDKContainerChildControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/navigatorTitle"},{"value":"startWithPresent:with:","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Coordinator~1start(present:with:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"startWithPresent:with:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1Coordinator~1start(present:with:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}