{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType\/localizedLabel"},"abstract":[{"type":"text","text":"Nav bar button with localized label for request creation."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"ZDKNavBarCreateRequestUITypeLocalizedLabel"}],"role":"symbol","symbolKind":"case","modules":[{"name":"SupportSDK"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedLabel"}],"externalID":"c:@E@ZDKNavBarCreateRequestUIType@ZDKNavBarCreateRequestUITypeLocalizedLabel","roleHeading":"Case","title":"ZDKNavBarCreateRequestUIType.localizedLabel"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedLabel","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdknavbarcreaterequestuitype\/localizedlabel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdknavbarcreaterequestuitype\/localizedlabel"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKNavBarCreateRequestUIType/localizedLabel":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedLabel"}],"title":"ZDKNavBarCreateRequestUIType.localizedLabel","kind":"symbol","abstract":[{"type":"text","text":"Nav bar button with localized label for request creation."}],"url":"\/documentation\/supportsdk\/zdknavbarcreaterequestuitype\/localizedlabel","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType\/localizedLabel","navigatorTitle":[{"kind":"identifier","text":"ZDKNavBarCreateRequestUITypeLocalizedLabel"}],"role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKNavBarCreateRequestUIType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKNavBarCreateRequestUIType","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKNavBarCreateRequestUIType","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Enum to describe the types of nav bar button that display request creation.","type":"text"}],"url":"\/documentation\/supportsdk\/zdknavbarcreaterequestuitype","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKNavBarCreateRequestUIType","title":"ZDKNavBarCreateRequestUIType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ZDKNavBarCreateRequestUITypeLocalizedLabel"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ZDKNavBarCreateRequestUITypeLocalizedLabel","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"ZDKNavBarCreateRequestUITypeLocalizedLabel","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType~1localizedLabel\/title","op":"replace","value":"ZDKNavBarCreateRequestUITypeLocalizedLabel"},{"op":"replace","value":[{"text":"ZDKNavBarCreateRequestUITypeLocalizedLabel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType~1localizedLabel\/fragments"},{"op":"replace","value":"ZDKNavBarCreateRequestUIType","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKNavBarCreateRequestUIType"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType\/fragments"},{"op":"replace","value":[{"text":"ZDKNavBarCreateRequestUIType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKNavBarCreateRequestUIType\/navigatorTitle"}]}]}