{"variants":[{"paths":["\/documentation\/supportsdk\/zdktoastviewwrapper\/hidetoastview(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/zdktoastviewwrapper\/hidetoastview(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/hideToastView(_:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideToastView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"hideToastView:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hideToastView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","modules":[{"name":"SupportSDK"}],"title":"hideToastView(_:)","externalID":"c:objc(cs)ZDKToastViewWrapper(im)hideToastView:"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKToastViewWrapper":{"url":"\/documentation\/supportsdk\/zdktoastviewwrapper","title":"ZDKToastViewWrapper","navigatorTitle":[{"text":"ZDKToastViewWrapper","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKToastViewWrapper","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper","type":"topic","kind":"symbol","abstract":[]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKToastViewWrapper/hideToastView(_:)":{"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideToastView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKToastViewWrapper\/hideToastView(_:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hideToastView:"}],"title":"hideToastView(_:)","url":"\/documentation\/supportsdk\/zdktoastviewwrapper\/hidetoastview(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"hideToastView:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hideToastView:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"hideToastView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"hide"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper\/title","op":"replace","value":"ZDKToastViewWrapper"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKToastViewWrapper"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ZDKToastViewWrapper"}]},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper~1hideToastView(_:)\/title","op":"replace","value":"hideToastView:"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKToastViewWrapper~1hideToastView(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"hideToastView:","kind":"identifier"}]}]}]}