{"variants":[{"paths":["\/documentation\/supportsdk\/articleuiconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/supportsdk\/articleuiconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/@M@SDKConfigurations@objc(pl)ZDKConfiguration","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleUiConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"ArticleUiConfiguration"}],"symbolKind":"class","title":"ArticleUiConfiguration","externalID":"c:@M@SupportSDK@objc(cs)ZDKArticleUiConfiguration","modules":[{"name":"SupportSDK"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(ZDKArticleUiConfiguration) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleUiConfiguration"}]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"content":[{"inlineContent":[{"text":"2.3.0","type":"text"}],"type":"paragraph"}],"style":"note","type":"aside","name":"Version"}]}],"abstract":[{"type":"text","text":"Data class used to configure Article Screen"}],"topicSections":[{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration\/init()"]},{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration\/engines","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration\/objcEngines","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration\/showContactOptions"]},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration\/isEqual(_:)"]}],"sections":[],"references":{"doc://com.zendesk.SupportSDK/@M@SDKConfigurations@objc(pl)ZDKConfiguration":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/@M@SDKConfigurations@objc(pl)ZDKConfiguration","title":"ZDKConfiguration"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ArticleUiConfiguration":{"title":"ArticleUiConfiguration","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ArticleUiConfiguration"}],"abstract":[{"type":"text","text":"Data class used to configure Article Screen"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ArticleUiConfiguration"}],"type":"topic","url":"\/documentation\/supportsdk\/articleuiconfiguration"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ArticleUiConfiguration/showContactOptions":{"url":"\/documentation\/supportsdk\/articleuiconfiguration\/showcontactoptions","role":"symbol","kind":"symbol","title":"showContactOptions","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showContactOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"showContactOptions"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration\/showContactOptions","abstract":[{"text":"Show the ","type":"text"},{"type":"codeVoice","code":"Contact Support"},{"text":" button in the help center’s article view","type":"text"}]},"doc://com.zendesk.SupportSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ArticleUiConfiguration/isEqual(_:)":{"url":"\/documentation\/supportsdk\/articleuiconfiguration\/isequal(_:)","type":"topic","abstract":[],"title":"isEqual(_:)","role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration\/isEqual(_:)","kind":"symbol"},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.zendesk.SupportSDK/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ","title":"Swift.Equatable"},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ArticleUiConfiguration/init()":{"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","abstract":[],"title":"init()","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration\/init()","type":"topic","url":"\/documentation\/supportsdk\/articleuiconfiguration\/init()"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ArticleUiConfiguration/engines":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration\/engines","abstract":[{"text":"The ","type":"text"},{"code":"Contact Support","type":"codeVoice"},{"text":" button on the Help Center Article screen will route to the “UMI” screen,","type":"text"},{"text":" ","type":"text"},{"text":"if an engine is added to this array. If the array is empty, we route to the ","type":"text"},{"code":"Request List","type":"codeVoice"},{"text":" screen if","type":"text"},{"text":" ","type":"text"},{"code":"Conversations","type":"codeVoice"},{"text":" are turned on, otherwise we will route to the ","type":"text"},{"code":"Request Screen","type":"codeVoice"},{"text":".","type":"text"}],"title":"engines","url":"\/documentation\/supportsdk\/articleuiconfiguration\/engines","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"engines","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Engine","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI6EngineP"},{"text":"]","kind":"text"}],"kind":"symbol","type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ArticleUiConfiguration/objcEngines":{"role":"symbol","deprecated":true,"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration\/objcEngines","abstract":[{"type":"text","text":"The "},{"code":"Contact Support","type":"codeVoice"},{"type":"text","text":" button on the Help Center Article screen will route to the “UMI” screen,"},{"type":"text","text":" "},{"type":"text","text":"if an engine is added to this array. If the array is empty, we route to the "},{"code":"Request List","type":"codeVoice"},{"type":"text","text":" screen if"},{"type":"text","text":" "},{"code":"Conversations","type":"codeVoice"},{"type":"text","text":" are turned on, otherwise we will route to the "},{"code":"Request Screen","type":"codeVoice"},{"type":"text","text":"."}],"title":"objcEngines","url":"\/documentation\/supportsdk\/articleuiconfiguration\/objcengines","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"objcEngines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MessagingAPI@objc(pl)ZDKEngine","text":"ZDKEngine"},{"kind":"text","text":"]"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"objcEngines"}]},"doc://com.zendesk.SupportSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SH","title":"Swift.Hashable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKArticleUiConfiguration","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ZDKArticleUiConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"ZDKArticleUiConfiguration","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration\/objcEngines","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration\/showContactOptions"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration\/init()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ArticleUiConfiguration\/isEqual(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/@M@SDKConfigurations@objc(pl)ZDKConfiguration"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKArticleUiConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKArticleUiConfiguration","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKArticleUiConfiguration"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration\/fragments"},{"op":"replace","value":[{"text":"ZDKArticleUiConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration\/navigatorTitle"},{"op":"replace","value":"showContactOptions","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration~1showContactOptions\/title"},{"op":"replace","value":[{"text":"showContactOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration~1showContactOptions\/fragments"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration~1isEqual(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration~1isEqual(_:)\/fragments"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration~1init()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration~1init()\/fragments"},{"op":"replace","value":"objcEngines","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration~1objcEngines\/title"},{"op":"replace","value":[{"kind":"identifier","text":"objcEngines"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ArticleUiConfiguration~1objcEngines\/fragments"}]}]}