{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/@M@SDKConfigurations@objc(pl)ZDKConfiguration","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"text":"HelpCenterUiConfiguration","kind":"identifier"}],"externalID":"c:@M@SupportSDK@objc(cs)ZDKHelpCenterUiConfiguration","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HelpCenterUiConfiguration","kind":"identifier"}],"roleHeading":"Class","role":"symbol","title":"HelpCenterUiConfiguration"},"sections":[],"topicSections":[{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/init()"],"title":"Initializers"},{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/engines","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/groupIds","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/groupType","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/labels","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/objcEngines","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/overviewContentModel","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/showContactOptions","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/showContactOptionsOnEmptySearch"],"title":"Instance Properties"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(ZDKHelpCenterUiConfiguration) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HelpCenterUiConfiguration","kind":"identifier"}]}],"kind":"declarations"},{"content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"name":"Version","type":"aside","style":"note","content":[{"inlineContent":[{"type":"text","text":"2.0.0"}],"type":"paragraph"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Data class used to configure Help Center"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/helpcenteruiconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/helpcenteruiconfiguration"]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration/groupType":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/groupType","title":"groupType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"groupType"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@ZDKHelpCenterOverviewGroupType","text":"ZDKHelpCenterOverviewGroupType"}],"url":"\/documentation\/supportsdk\/helpcenteruiconfiguration\/grouptype","abstract":[{"text":"The type of ids being used.","type":"text"}]},"doc://com.zendesk.SupportSDK/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject","title":"NSObject"},"doc://com.zendesk.SupportSDK/SQ":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration/init()":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init()","type":"topic","url":"\/documentation\/supportsdk\/helpcenteruiconfiguration\/init()","abstract":[{"text":"Returns a default model. To customize the content, update properties on a default model.","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration/overviewContentModel":{"role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/overviewContentModel","title":"overviewContentModel","kind":"symbol","navigatorTitle":[{"text":"overviewContentModel","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"overviewContentModel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ZDKHelpCenterOverviewContentModel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)ZDKHelpCenterOverviewContentModel"}],"url":"\/documentation\/supportsdk\/helpcenteruiconfiguration\/overviewcontentmodel","abstract":[]},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.zendesk.SupportSDK/@M@SDKConfigurations@objc(pl)ZDKConfiguration":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/@M@SDKConfigurations@objc(pl)ZDKConfiguration","title":"ZDKConfiguration"},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration/engines":{"abstract":[{"text":"The ","type":"text"},{"code":"Contact Support","type":"codeVoice"},{"text":" button on the Help Center Article screen will route to the “UMI” screen,","type":"text"},{"text":" ","type":"text"},{"text":"if an engine is added to this array. If the array is empty, we route to the ","type":"text"},{"code":"Request List","type":"codeVoice"},{"text":" screen if","type":"text"},{"text":" ","type":"text"},{"code":"Conversations","type":"codeVoice"},{"text":" are turned on, otherwise we will route to the ","type":"text"},{"code":"Request Screen","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/supportsdk\/helpcenteruiconfiguration\/engines","title":"engines","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"engines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Engine","preciseIdentifier":"s:12MessagingAPI6EngineP"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/engines"},"doc://com.zendesk.SupportSDK/SH":{"type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SH","title":"Swift.Hashable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration/groupIds":{"abstract":[{"text":"A list of ids. Only show articles contained in the categories\/sections.","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"groupIds","kind":"identifier"},{"text":": [","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/groupIds","title":"groupIds","url":"\/documentation\/supportsdk\/helpcenteruiconfiguration\/groupids","role":"symbol","navigatorTitle":[{"text":"groupIds","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration/showContactOptionsOnEmptySearch":{"url":"\/documentation\/supportsdk\/helpcenteruiconfiguration\/showcontactoptionsonemptysearch","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showContactOptionsOnEmptySearch","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","title":"showContactOptionsOnEmptySearch","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/showContactOptionsOnEmptySearch","abstract":[{"text":"Show the ","type":"text"},{"type":"codeVoice","code":"Contact Support"},{"text":" button in the Help Center empty search result screen","type":"text"},{"text":" ","type":"text"},{"text":"true by default","type":"text"}],"navigatorTitle":[{"text":"showContactOptionsOnEmptySearch","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration":{"kind":"symbol","role":"symbol","title":"HelpCenterUiConfiguration","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HelpCenterUiConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"HelpCenterUiConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Data class used to configure Help Center"}],"url":"\/documentation\/supportsdk\/helpcenteruiconfiguration"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration/objcEngines":{"title":"objcEngines","kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"Contact Support"},{"type":"text","text":" button on the Help Center Article screen will route to the “UMI” screen,"},{"type":"text","text":" "},{"type":"text","text":"if an engine is added to this array. If the array is empty, we route to the "},{"type":"codeVoice","code":"Request List"},{"type":"text","text":" screen if"},{"type":"text","text":" "},{"type":"codeVoice","code":"Conversations"},{"type":"text","text":" are turned on, otherwise we will route to the "},{"type":"codeVoice","code":"Request Screen"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/objcEngines","navigatorTitle":[{"kind":"identifier","text":"objcEngines"}],"type":"topic","role":"symbol","url":"\/documentation\/supportsdk\/helpcenteruiconfiguration\/objcengines","deprecated":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"objcEngines"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@MessagingAPI@objc(pl)ZDKEngine","kind":"typeIdentifier","text":"ZDKEngine"},{"kind":"text","text":"]"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration/showContactOptions":{"abstract":[{"type":"text","text":"Show the "},{"type":"codeVoice","code":"Contact Support"},{"type":"text","text":" button in the Help Center main screen"},{"type":"text","text":" "},{"type":"text","text":"true by default"}],"navigatorTitle":[{"kind":"identifier","text":"showContactOptions"}],"title":"showContactOptions","type":"topic","url":"\/documentation\/supportsdk\/helpcenteruiconfiguration\/showcontactoptions","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/showContactOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"showContactOptions"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/HelpCenterUiConfiguration/labels":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"labels"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"labels"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"url":"\/documentation\/supportsdk\/helpcenteruiconfiguration\/labels","kind":"symbol","abstract":[{"type":"text","text":"A list of labels to which must be present for an article to show up in the list."}],"title":"labels","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/labels","role":"symbol"},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ZDKHelpCenterUiConfiguration","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterUiConfiguration"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"ZDKHelpCenterUiConfiguration","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/groupIds","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/groupType","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/labels","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/objcEngines","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/overviewContentModel","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/showContactOptions","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/showContactOptionsOnEmptySearch"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/HelpCenterUiConfiguration\/init()"],"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/@M@SDKConfigurations@objc(pl)ZDKConfiguration"],"title":"Conforms To"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterUiConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"groupType","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1groupType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"groupType"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1groupType\/fragments","op":"replace"},{"value":"init","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1init()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1init()\/fragments","op":"replace"},{"value":"overviewContentModel","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1overviewContentModel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"overviewContentModel"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1overviewContentModel\/fragments","op":"replace"},{"value":"groupIds","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1groupIds\/title","op":"replace"},{"value":[{"text":"groupIds","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1groupIds\/fragments","op":"replace"},{"value":"showContactOptionsOnEmptySearch","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1showContactOptionsOnEmptySearch\/title","op":"replace"},{"value":[{"text":"showContactOptionsOnEmptySearch","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1showContactOptionsOnEmptySearch\/fragments","op":"replace"},{"value":"ZDKHelpCenterUiConfiguration","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration\/title","op":"replace"},{"value":[{"text":"ZDKHelpCenterUiConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterUiConfiguration"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration\/navigatorTitle","op":"replace"},{"value":"objcEngines","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1objcEngines\/title","op":"replace"},{"value":[{"text":"objcEngines","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1objcEngines\/fragments","op":"replace"},{"value":"showContactOptions","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1showContactOptions\/title","op":"replace"},{"value":[{"text":"showContactOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1showContactOptions\/fragments","op":"replace"},{"value":"labels","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1labels\/title","op":"replace"},{"value":[{"kind":"identifier","text":"labels"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1HelpCenterUiConfiguration~1labels\/fragments","op":"replace"}]}]}