{"kind":"symbol","metadata":{"modules":[{"name":"SupportSDK"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterConversationsUIDelegate"}],"roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterConversationsUIDelegate"}],"externalID":"c:objc(pl)ZDKHelpCenterConversationsUIDelegate","symbolKind":"protocol","platforms":[{"deprecated":true,"beta":false,"unavailable":false,"message":"use ZDKHelpCenterUiConfiguration and ZDKArticleUiConfiguration to configure the 'contact us' button on their respective screens "}],"role":"symbol","title":"ZDKHelpCenterConversationsUIDelegate"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"]}],"sections":[],"topicSections":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate\/active()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate\/conversationsBarButtonImage()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate\/conversationsBarButtonLocalizedLabel()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate\/navBarConversationsUIType()"]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"use ZDKHelpCenterUiConfiguration and ZDKArticleUiConfiguration to configure the 'contact us' button on their respective screens "}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterConversationsUIDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}]}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate","interfaceLanguage":"swift"},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterConversationsUIDelegate":{"abstract":[],"navigatorTitle":[{"text":"ZDKHelpCenterConversationsUIDelegate","kind":"identifier"}],"url":"\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate","deprecated":true,"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterConversationsUIDelegate","kind":"identifier"}],"title":"ZDKHelpCenterConversationsUIDelegate","type":"topic","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterConversationsUIDelegate/conversationsBarButtonImage()":{"kind":"symbol","title":"conversationsBarButtonImage()","url":"\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate\/conversationsbarbuttonimage()","abstract":[{"type":"text","text":"To conform implementations should return an image for the right nav bar button."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate\/conversationsBarButtonImage()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"conversationsBarButtonImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"!","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"conversationsBarButtonImage","kind":"identifier"}],"deprecated":true,"role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterConversationsUIDelegate/conversationsBarButtonLocalizedLabel()":{"kind":"symbol","title":"conversationsBarButtonLocalizedLabel()","url":"\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate\/conversationsbarbuttonlocalizedlabel()","abstract":[{"type":"text","text":"To conform implementations should return a localized string for the right nav bar button title."}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate\/conversationsBarButtonLocalizedLabel()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationsBarButtonLocalizedLabel","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"!","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"conversationsBarButtonLocalizedLabel","kind":"identifier"}],"deprecated":true,"role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterConversationsUIDelegate/navBarConversationsUIType()":{"deprecated":true,"kind":"symbol","url":"\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate\/navbarconversationsuitype()","role":"symbol","required":true,"abstract":[{"type":"text","text":"To conform implementations should return the conversations UI type desired."}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate\/navBarConversationsUIType()","title":"navBarConversationsUIType()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"navBarConversationsUIType","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"ZDKNavBarConversationsUIType","kind":"typeIdentifier","preciseIdentifier":"c:@E@ZDKNavBarConversationsUIType"}],"navigatorTitle":[{"text":"navBarConversationsUIType","kind":"identifier"}]},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterConversationsUIDelegate/active()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"active","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"ZDKContactUsVisibility","kind":"typeIdentifier","preciseIdentifier":"c:@E@ZDKContactUsVisibility"}],"navigatorTitle":[{"text":"active","kind":"identifier"}],"role":"symbol","type":"topic","required":true,"url":"\/documentation\/supportsdk\/zdkhelpcenterconversationsuidelegate\/active()","deprecated":true,"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate\/active()","title":"active()","abstract":[{"text":"Determines where the coversations nav bar button will be displayed.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"beta":false,"deprecated":true,"unavailable":false}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKHelpCenterConversationsUIDelegate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterConversationsUIDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"ZDKHelpCenterConversationsUIDelegate"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate\/active()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate\/conversationsBarButtonImage()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate\/conversationsBarButtonLocalizedLabel()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterConversationsUIDelegate\/navBarConversationsUIType()"]}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterConversationsUIDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":[{"type":"paragraph","inlineContent":[{"text":"use ZDKHelpCenterUiConfiguration and ZDKArticleUiConfiguration to configure the 'contact us' button on their respective screens ","type":"text"}]}],"op":"replace","path":"\/deprecationSummary"},{"value":"ZDKHelpCenterConversationsUIDelegate","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate\/title"},{"value":[{"text":"ZDKHelpCenterConversationsUIDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate\/fragments"},{"value":[{"text":"ZDKHelpCenterConversationsUIDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate\/navigatorTitle"},{"value":"conversationsBarButtonImage","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate~1conversationsBarButtonImage()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"conversationsBarButtonImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate~1conversationsBarButtonImage()\/fragments"},{"value":"conversationsBarButtonLocalizedLabel","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate~1conversationsBarButtonLocalizedLabel()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"conversationsBarButtonLocalizedLabel"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate~1conversationsBarButtonLocalizedLabel()\/fragments"},{"value":"navBarConversationsUIType","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate~1navBarConversationsUIType()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"navBarConversationsUIType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate~1navBarConversationsUIType()\/fragments"},{"value":"active","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate~1active()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"active","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterConversationsUIDelegate~1active()\/fragments"}]}]}