{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"ZDKHelpCenterNoCategoriesLocalisedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterNoCategoriesLocalisedDescription"},"sections":[],"abstract":[{"type":"text","text":"Error description for category id error."}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"metadata":{"modules":[{"name":"SupportSDK"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKHelpCenterNoCategoriesLocalisedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"ZDKHelpCenterNoCategoriesLocalisedDescription","externalID":"c:@ZDKHelpCenterNoCategoriesLocalisedDescription","symbolKind":"var","role":"symbol","navigatorTitle":[{"text":"ZDKHelpCenterNoCategoriesLocalisedDescription","kind":"identifier"}],"roleHeading":"Global Variable"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenternocategorieslocaliseddescription"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkhelpcenternocategorieslocaliseddescription"]}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKHelpCenterNoCategoriesLocalisedDescription":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Error description for category id error."}],"navigatorTitle":[{"kind":"identifier","text":"ZDKHelpCenterNoCategoriesLocalisedDescription"}],"url":"\/documentation\/supportsdk\/zdkhelpcenternocategorieslocaliseddescription","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKHelpCenterNoCategoriesLocalisedDescription","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterNoCategoriesLocalisedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"ZDKHelpCenterNoCategoriesLocalisedDescription","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"ZDKHelpCenterNoCategoriesLocalisedDescription"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterNoCategoriesLocalisedDescription"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKHelpCenterNoCategoriesLocalisedDescription"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterNoCategoriesLocalisedDescription\/title","op":"replace","value":"ZDKHelpCenterNoCategoriesLocalisedDescription"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKHelpCenterNoCategoriesLocalisedDescription\/fragments","op":"replace","value":[{"kind":"identifier","text":"ZDKHelpCenterNoCategoriesLocalisedDescription"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}