{"metadata":{"role":"symbol","title":"ZDKLayoutGuideApplicator","externalID":"c:objc(cs)ZDKLayoutGuideApplicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKLayoutGuideApplicator"}],"symbolKind":"class","modules":[{"name":"SupportSDK"}],"navigatorTitle":[{"kind":"identifier","text":"ZDKLayoutGuideApplicator"}],"roleHeading":"Class"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdklayoutguideapplicator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdklayoutguideapplicator"]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"kind":"symbol","abstract":[{"type":"text","text":"This class tries to fix the layout spacing when using XIB instead of storyboard."},{"type":"text","text":" "},{"type":"text","text":"Since we cannot reference the top\/bottom layout guids. This class fixes the top\/bottom layout to be relative to the guides."}],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicator\/init(viewController:topLevel:layoutPosition:)"],"title":"Initializers","anchor":"Initializers","generated":true}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKLayoutGuideApplicator","kind":"identifier"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicator","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP","doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP","doc:\/\/com.zendesk.SupportSDK\/SQ","doc:\/\/com.zendesk.SupportSDK\/SH"],"title":"Conforms To","type":"conformsTo"}],"references":{"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.zendesk.SupportSDK/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"},"doc://com.zendesk.SupportSDK/SH":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.zendesk.SupportSDK/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s7CVarArgP"},"doc://com.zendesk.SupportSDK/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.zendesk.SupportSDK/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/SQ"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicator/init(viewController:topLevel:layoutPosition:)":{"title":"init(viewController:topLevel:layoutPosition:)","role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"topLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layoutPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ZDKLayoutGuideApplicatorPosition","preciseIdentifier":"c:@E@ZDKLayoutGuideApplicatorPosition"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Creates an instance"}],"kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicator\/init(viewController:topLevel:layoutPosition:)","navigatorTitle":[{"kind":"identifier","text":"initWithViewController:topLevelView:layoutPosition:"}],"url":"\/documentation\/supportsdk\/zdklayoutguideapplicator\/init(viewcontroller:toplevel:layoutposition:)"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.zendesk.SupportSDK\/s23CustomStringConvertibleP"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKLayoutGuideApplicator":{"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicator","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ZDKLayoutGuideApplicator"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKLayoutGuideApplicator"}],"url":"\/documentation\/supportsdk\/zdklayoutguideapplicator","title":"ZDKLayoutGuideApplicator","abstract":[{"text":"This class tries to fix the layout spacing when using XIB instead of storyboard.","type":"text"},{"text":" ","type":"text"},{"text":"Since we cannot reference the top\/bottom layout guids. This class fixes the top\/bottom layout to be relative to the guides.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ZDKLayoutGuideApplicator","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ZDKLayoutGuideApplicator"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"ZDKLayoutGuideApplicator"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKLayoutGuideApplicator\/init(viewController:topLevel:layoutPosition:)"],"generated":true,"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ZDKLayoutGuideApplicator"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicator~1init(viewController:topLevel:layoutPosition:)\/title","value":"initWithViewController:topLevelView:layoutPosition:","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicator~1init(viewController:topLevel:layoutPosition:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithViewController:topLevelView:layoutPosition:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicator\/title","value":"ZDKLayoutGuideApplicator","op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicator\/fragments","value":[{"text":"ZDKLayoutGuideApplicator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKLayoutGuideApplicator\/navigatorTitle","value":[{"text":"ZDKLayoutGuideApplicator","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}