{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKSpinnerDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/zdkspinnerdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/zdkspinnerdelegate"]}],"metadata":{"title":"ZDKSpinnerDelegate","externalID":"c:objc(pl)ZDKSpinnerDelegate","modules":[{"name":"SupportSDK"}],"symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"ZDKSpinnerDelegate"}],"roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKSpinnerDelegate","kind":"identifier"}],"role":"symbol"},"kind":"symbol","abstract":[{"type":"text","text":"Spinner control delegate."}],"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate\/center","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate\/frame","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate\/isHidden"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate\/startAnimating()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate\/stopAnimating()"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From"}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSpinnerDelegate":{"url":"\/documentation\/supportsdk\/zdkspinnerdelegate","type":"topic","title":"ZDKSpinnerDelegate","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKSpinnerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKSpinnerDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Spinner control delegate."}],"role":"symbol","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSpinnerDelegate/isHidden":{"url":"\/documentation\/supportsdk\/zdkspinnerdelegate\/ishidden","type":"topic","title":"isHidden","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate\/isHidden","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isHidden"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"hidden"}],"abstract":[{"text":"Is the spinner hidden? YES or NO.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSpinnerDelegate/frame":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"role":"symbol","title":"frame","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate\/frame","type":"topic","url":"\/documentation\/supportsdk\/zdkspinnerdelegate\/frame","required":true,"navigatorTitle":[{"kind":"identifier","text":"frame"}],"kind":"symbol","abstract":[{"text":"Frame of spinner.","type":"text"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSpinnerDelegate/startAnimating()":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate\/startAnimating()","required":true,"url":"\/documentation\/supportsdk\/zdkspinnerdelegate\/startanimating()","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAnimating"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"startAnimating"}],"title":"startAnimating()","abstract":[{"type":"text","text":"Start the spinner animating."}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSpinnerDelegate/center":{"title":"center","url":"\/documentation\/supportsdk\/zdkspinnerdelegate\/center","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate\/center","type":"topic","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"center","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"}],"abstract":[{"text":"The center of the view.","type":"text"}],"navigatorTitle":[{"text":"center","kind":"identifier"}],"kind":"symbol"},"doc://com.zendesk.SupportSDK/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKSpinnerDelegate/stopAnimating()":{"title":"stopAnimating()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopAnimating"},{"kind":"text","text":"()"}],"type":"topic","url":"\/documentation\/supportsdk\/zdkspinnerdelegate\/stopanimating()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"stopAnimating"}],"required":true,"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate\/stopAnimating()","role":"symbol","abstract":[{"text":"Stop the spinner animating.","type":"text"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ZDKSpinnerDelegate","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKSpinnerDelegate"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"ZDKSpinnerDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate\/center","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate\/frame","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate\/isHidden"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate\/startAnimating()","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKSpinnerDelegate\/stopAnimating()"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.zendesk.SupportSDK\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKSpinnerDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ZDKSpinnerDelegate","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate\/title"},{"op":"replace","value":[{"text":"ZDKSpinnerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKSpinnerDelegate"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate\/navigatorTitle"},{"op":"replace","value":"hidden","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate~1isHidden\/title"},{"op":"replace","value":[{"text":"hidden","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate~1isHidden\/fragments"},{"op":"replace","value":"frame","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate~1frame\/title"},{"op":"replace","value":[{"kind":"identifier","text":"frame"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate~1frame\/fragments"},{"op":"replace","value":"startAnimating","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate~1startAnimating()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startAnimating"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate~1startAnimating()\/fragments"},{"op":"replace","value":"center","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate~1center\/title"},{"op":"replace","value":[{"kind":"identifier","text":"center"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate~1center\/fragments"},{"op":"replace","value":"stopAnimating","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate~1stopAnimating()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stopAnimating","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKSpinnerDelegate~1stopAnimating()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}