{"metadata":{"roleHeading":"Instance Method","modules":[{"relatedModules":["MessagingAPI"],"name":"SupportSDK"}],"symbolKind":"method","role":"symbol","externalID":"s:12MessagingAPI10ObservablePAAE15notifyObserversyyABQzF::SYNTHESIZED::c:@M@SupportSDK@objc(cs)ZDKSupportEngine","extendedModule":"MessagingAPI","title":"notifyObservers(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notifyObservers","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Observable","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI10ObservablePABQa"},{"text":")","kind":"text"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Observable.notifyObservers(_:)","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/notifyObservers(_:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notifyObservers","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"observable","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:12MessagingAPI10ObservablePABQa","text":"Observable","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/supportsdk\/supportengine\/notifyobservers(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine"]]},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine","title":"SupportEngine","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupportEngine"}],"navigatorTitle":[{"kind":"identifier","text":"SupportEngine"}],"abstract":[],"url":"\/documentation\/supportsdk\/supportengine"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine/notifyObservers(_:)":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/notifyObservers(_:)","url":"\/documentation\/supportsdk\/supportengine\/notifyobservers(_:)","title":"notifyObservers(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notifyObservers","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Observable","kind":"typeIdentifier","preciseIdentifier":"s:12MessagingAPI10ObservablePABQa"},{"text":")","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"ZDKSupportEngine","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine\/title"},{"op":"replace","value":[{"text":"ZDKSupportEngine","kind":"identifier"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKSupportEngine"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine\/navigatorTitle"}]}]}