{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/supportsdk\/supportengine\/stop()"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"externalID":"s:10SupportSDK0A6EngineC4stopyyF","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"title":"stop()","modules":[{"name":"SupportSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/stop()","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Engine.stop()"},{"type":"text","text":"."}],"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine/stop()":{"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[],"url":"\/documentation\/supportsdk\/supportengine\/stop()","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine\/stop()","title":"stop()","role":"symbol"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/SupportEngine":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/SupportEngine","title":"SupportEngine","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SupportEngine"}],"navigatorTitle":[{"kind":"identifier","text":"SupportEngine"}],"abstract":[],"url":"\/documentation\/supportsdk\/supportengine"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ZDKSupportEngine","op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine\/title"},{"value":[{"kind":"identifier","text":"ZDKSupportEngine"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine\/fragments"},{"value":[{"text":"ZDKSupportEngine","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1SupportEngine\/navigatorTitle"}]}]}