{"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/supportsdk\/containerchildcontrollerdelegate\/willdismiss()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/supportsdk\/containerchildcontrollerdelegate\/willdismiss()"]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate\/willDismiss()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willDismiss","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"required":true,"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"SupportSDK"}],"title":"willDismiss()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willDismiss","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"method","externalID":"c:@M@SupportSDK@objc(pl)ZDKContainerChildControllerDelegate(im)willDismiss","navigatorTitle":[{"text":"willDismiss","kind":"identifier"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChildControllerDelegate/willDismiss()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willDismiss"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate\/willDismiss()","kind":"symbol","title":"willDismiss()","required":true,"url":"\/documentation\/supportsdk\/containerchildcontrollerdelegate\/willdismiss()","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"willDismiss"}]},"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ContainerChildControllerDelegate":{"abstract":[],"role":"symbol","type":"topic","title":"ContainerChildControllerDelegate","url":"\/documentation\/supportsdk\/containerchildcontrollerdelegate","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ContainerChildControllerDelegate","navigatorTitle":[{"text":"ContainerChildControllerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContainerChildControllerDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"willDismiss"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"willDismiss","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"willDismiss"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate~1willDismiss()\/title","value":"willDismiss"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate~1willDismiss()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"willDismiss","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/title","value":"ZDKContainerChildControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/fragments","value":[{"text":"ZDKContainerChildControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ContainerChildControllerDelegate\/navigatorTitle","value":[{"text":"ZDKContainerChildControllerDelegate","kind":"identifier"}]}]}]}