{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/Equatable-Implementations"},"topicSections":[{"identifiers":["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/!=(_:_:)"],"generated":true,"anchor":"Operators","title":"Operators"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/supportsdk\/zdkcontactusvisibility\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"metadata":{"role":"collectionGroup","modules":[{"name":"SupportSDK"}],"title":"Equatable Implementations","roleHeading":"API Collection"},"hierarchy":{"paths":[["doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility"]]},"kind":"article","references":{"doc://com.zendesk.SupportSDK/documentation/SupportSDK":{"title":"SupportSDK","url":"\/documentation\/supportsdk","kind":"symbol","identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK","role":"collection","abstract":[],"type":"topic"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKContactUsVisibility":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ZDKContactUsVisibility","kind":"identifier"}],"navigatorTitle":[{"text":"ZDKContactUsVisibility","kind":"identifier"}],"abstract":[{"text":"Used to select where conversations nav bar button will be active.","type":"text"}],"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility","kind":"symbol","type":"topic","deprecated":true,"role":"symbol","url":"\/documentation\/supportsdk\/zdkcontactusvisibility","title":"ZDKContactUsVisibility"},"doc://com.zendesk.SupportSDK/documentation/SupportSDK/ZDKContactUsVisibility/!=(_:_:)":{"identifier":"doc:\/\/com.zendesk.SupportSDK\/documentation\/SupportSDK\/ZDKContactUsVisibility\/!=(_:_:)","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","url":"\/documentation\/supportsdk\/zdkcontactusvisibility\/!=(_:_:)","title":"!=(_:_:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"ZDKContactUsVisibility","path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKContactUsVisibility"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ZDKContactUsVisibility"}],"path":"\/references\/doc:~1~1com.zendesk.SupportSDK~1documentation~1SupportSDK~1ZDKContactUsVisibility\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}